CREATE TABLE papers (
    id SERIAL PRIMARY KEY,
    doi VARCHAR(255) UNIQUE,
    arxiv_id VARCHAR(100),
    semantic_scholar_id VARCHAR(100),
    title TEXT NOT NULL,
    abstract TEXT,
    publication_year INTEGER,
    citation_count INTEGER DEFAULT 0,
    journal VARCHAR(500),
    venue VARCHAR(500),
    authors_text TEXT,
    page_rank_score REAL DEFAULT 0.0,
    cluster_id INTEGER,
    publication_date DATE,
    fields_of_study TEXT[],
    url VARCHAR(1000),
    pdf_url VARCHAR(1000),
    s2_paper_id VARCHAR(100),
    openalex_id VARCHAR(255),
    crossref_type VARCHAR(100),
    is_open_access BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);